image: ubuntu:devel

stages:
    - static_analysis

static_analysis:
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -y
    - apt-get install python3 python3-pip python3-dbus  -y
    - python3 -m pip install flake8

  script:
    - cd plugins
    - flake8 --select=F --ignore=F401,F841

